name: Run pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: gates-tldrd-runners

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e.

    - name: Run pytest
      run: |
        pytest
